In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("../data/raw/materials_data.csv")

df.head()

,formula_pretty,density,material_id,formation_energy_per_atom,energy_above_hull,band_gap,is_metal,fields_not_requested
0,Ac,8.157868,mp-ovi,0.021639,0.021639,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme..."
1,Ac,8.313274,mp-cpicf,0.015586,0.015586,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme..."
2,Ac,8.144760,mp-cpicr,0.011822,0.011822,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme..."
3,Ac,8.170182,mp-bxcek,0.000000,0.000000,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme..."
4,Ac2AgIr,11.367264,mp-bxatg,-0.413285,0.087118,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme..."

In [14]:
df.describe()

,density,formation_energy_per_atom,energy_above_hull,band_gap
count,20000.000000,20000.000000,20000.000000,20000.000000
mean,5.158009,-1.424898,0.184905,1.083421
std,2.467925,1.274775,0.431002,1.589616
min,0.039581,-4.467987,0.000000,0.000000
25%,3.466884,-2.469185,0.000157,0.000000
50%,4.889375,-1.393702,0.038767,0.027400
75%,6.546139,-0.431707,0.169252,1.876125
max,18.889325,5.474543,7.322514,9.065300

In [15]:
df.info()
df.isnull().sum()

# There aren't nulls. The info is correct

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   formula_pretty             20000 non-null  object
 1   density                    20000 non-null  float64
 2   material_id                20000 non-null  object
 3   formation_energy_per_atom  20000 non-null  float64
 4   energy_above_hull          20000 non-null  float64
 5   band_gap                   20000 non-null  float64
 6   is_metal                   20000 non-null  bool
 7   fields_not_requested       20000 non-null  object
dtypes: bool(1), float64(4), object(3)
memory usage: 1.1+ MB

formula_pretty               0
density                      0
material_id                  0
formation_energy_per_atom    0
energy_above_hull            0
band_gap                     0
is_metal                     0
fields_not_requested         0
dtype: int64

In [21]:
c = df.duplicated().sum()
print("Number of duplicates:", c)

Number of duplicates: 0

In [22]:
# Recompute number of elements
df["num_elements"] = df["formula_pretty"].apply(lambda x: len(set([c for c in x if c.isupper()])))

In [23]:
df.head()

,formula_pretty,density,material_id,formation_energy_per_atom,energy_above_hull,band_gap,is_metal,fields_not_requested,num_elements
0,Ac,8.157868,mp-ovi,0.021639,0.021639,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme...",1
1,Ac,8.313274,mp-cpicf,0.015586,0.015586,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme...",1
2,Ac,8.144760,mp-cpicr,0.011822,0.011822,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme...",1
3,Ac,8.170182,mp-bxcek,0.000000,0.000000,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme...",1
4,Ac2AgIr,11.367264,mp-bxatg,-0.413285,0.087118,0.0,True,"['builder_meta', 'nsites', 'elements', 'neleme...",2

In [24]:
df.to_csv("../data/processed/materials_clean.csv", index=False)